### ISSUE TITLE
specific permissions related to post mortem research authorization

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#41]
Updated with Chris' help, ready for comment and submission to OBIB

Can also review in google document, here -request permission if you need it

 https://docs.google.com/spreadsheets/d/1p0Gtq3Id_xlJ8SFmeCGqLP-woBxhP28UFAGl7Yg363w/edit#gid=0

**Comment by fjmanion** [comment]
The way the definitions are written, you are conflating authorization with documentation of authorization. They are not necessarily the same. This impacts:
1) authorization for postmortem specimen donation for a specified purpose
2) authorization for post mortem specimen donation for transplantation purposes only
3) authorization for post mortem specimen donation for transplantation and research
4) authorization for post mortem specimen donation for research only

At the very least you should change the definition of these terms so it simply states they are the output of an authorization process. These terms are also subclassed to "research authorization documentation for post mortem specimen donation for a specified purpose" so that will need to be addressed also. Unless documentation is really an individually needed concern for each of these cases, then keep these terms, but change the definitions, and change the parent class to represent the outcome of an authorization process. Documentation of the authorization event should be added (if actually needed) to class dealing with documentation of the event. Note that IAO_0000572 'documenting' is a planned process with a specified input of an ICE, and specified output of a 'document' (IAO_0000310). 

I've also attached my copy of the spreadsheet with comments added for your convenience. It has all notes for tracker items 39, 40, and 41. Unfortunately, it's an Excel file...
[Consent form BBRB.xlsx](https://github.com/biobanking/biobanking/files/1271430/Consent.form.BBRB.xlsx)

**Comment by cstoeckert** [comment]
added as part of https://github.com/biobanking/ontology/commit/b95d7d6ca0d91dfc04b8beab14b9fd3390717e71
Now in OBIB release 2017-10-12
