### ISSUE TITLE
issues found in release preparation

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#50]
1.' Homo sapiens' is asserted as its own subClass in import_OBO.owl
2. 'specimen meeting specification' does not have definition but definition source. Is definition source should be definition?
3. 'study principle investigator or responsible' is asserted as 'material information bearer'. Is it what we want? The term does not have term editor information.

**Comment by cstoeckert** [comment]
Issues 2 and 3 are both present in the current release and are from OMIABIS. @mbrochhausen can you look at these and maybe we can fix?
Thanks, Chris

**Comment by cstoeckert** [comment]
issue 1 (Homo sapiens) is also in current release and appears to be imported from both NCBI Taxon and OMRSE.

**Comment by mbrochhausen** [comment]
I looked into issue 3 and I am fairly certain this is not a legacy OMIABIS issue. I think the issue stems from the axiom on OBI's 'investigation agent role'. As such, the inference should show up for all bearers of subclasses of investigation agent role. 
However, due to the "or" in the label and since this is rather something we might want to create in a query, I obsolete the class. If we want principle investigator again, I can easily create that.
**The obsoletion of the class does not make the problem obsolete, since it will show up again and again (s.a.) **

**Comment by mbrochhausen** [comment]
issue 2 resolved by https://github.com/biobanking/ontology/commit/d0f734ddf175069c0a84a2c8423ce85565aa923d

**Comment by mbrochhausen** [comment]
issue 3 resolved by https://github.com/biobanking/ontology/commit/2ca47b7afd7bd13215c02c046ed19dd80f6451c8

**Comment by cstoeckert** [comment]
issue one has been addressed by OMRSE.

**Comment by cstoeckert** [comment]
These have been addressed in the 2019-06-20 release.
