### ISSUE TITLE
Moving 'postal code' to subclass of 'identifier'

### ISSUE THREAD

**Issue by sjbost** [biobanking/biobanking#64]
Currently 'postal code' is a subclass of 'textual entity.' We propose moving it to be a subclass of 'identifier' as this is more accurate.

**Comment by mbrochhausen** [comment]
I agree. But we probably also need to change the definition: "A postal code is a textual entity that is a series of letters and/or digits and is part of a postal address for the purpose of sorting mail."
I propose: "An identifier that is created for purpose of sorting mail refer to geographical regions, postboxes, delivery routes or individual recipients."
With these changes I think we need to obsolete the class (and probably its subclasses) and create it (them) anew. The new class should not have "is about some geographical_region" as an axiom since that is not universally true.

**Comment by mbrochhausen** [comment]
Here are the outcomes of discussing these terms at an internal project meeting here are UF (including Bill Hogan, Clint Dowland, Matt Diller, Sarah Bost, Cara McDonnell and myself):
Here’s the material from the Google doc that you asked me to copy/paste into an email to you:
 
Postal delivery route: 

a plan specification that if realized, is realized by the delivery of mail to some facility or mailbox within some geographical region

Aggregate of postal delivery routes:

an aggregate whose members/components are only postal delivery routes

Postal code: 

an identifier that is part of a postal address for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes.

[Proposal: Make postal code a subclass of identifier (proper name), rather than a subclass of textual entity.]

·         For this approach to work, all postal codes would have to denote something.  Right now, we are only sure it works for US ZIP codes, and perhaps some others we looked at in a meeting.  We need to verify and DOCUMENT our findings.

Instead of the above, re-use an updated version of the OMIABIS definition, which is “a postal code is a textual entity that is a series of letters and/or digits and is part of a postal address for the purpose of sorting mail.”

Questions: is the version reproduced above the updated version?  Or were we waiting on an update that hasn’t happened yet, and if so, when is it to occur?  And also if so, who was doing the update?

Zip code:

a postal code that is used in the United States for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes

Postal delivery route: 

a plan specification that if realized, is realized by the delivery of mail to some facility or mailbox within some geographical region

Aggregate of postal delivery routes:

an aggregate whose members/components are only postal delivery routes

Postal code: 

an identifier that is part of a postal address for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes.

[Proposal: Make postal code a subclass of identifier (proper name), rather than a subclass of textual entity.]

·         For this approach to work, all postal codes would have to denote something.  Right now, we are only sure it works for US ZIP codes, and perhaps some others we looked at in a meeting.  We need to verify and DOCUMENT our findings.

Instead of the above, re-use an updated version of the OMIABIS definition, which is “a postal code is a textual entity that is a series of letters and/or digits and is part of a postal address for the purpose of sorting mail.”

Questions: is the version reproduced above the updated version?  Or were we waiting on an update that hasn’t happened yet, and if so, when is it to occur?  And also if so, who was doing the update?

Zip code:

a postal code that is used in the United States for the purpose of sorting and delivering mail, and that denotes some postal delivery route or some aggregate of postal delivery routes.

**Comment by zhengj2007** [comment]
Shall we move these terms in IAO?

**Comment by mbrochhausen** [comment]
What is the current curation statues of IAO?

Thanks,
Mathias

**Comment by zhengj2007** [comment]
@mbrochhausen If we can make agreement on OBIB, I can add the term in IAO and make the release.

**Comment by zhengj2007** [comment]
Have submitted NTRs to IAO issue tracker:
https://github.com/information-artifact-ontology/IAO/issues/226

**Comment by cstoeckert** [comment]
Need to import: http://purl.obolibrary.org/obo/IAO_0000646 and deprecate http://purl.obolibrary.org/obo/OMIABIS_0000026

**Comment by sjbost** [comment]
Should be fixed by 6ce97dbacdb53d5ac78c75a7ab093e39c4af4664
