### ISSUE TITLE
logical definition of biobank has unsatisfiable clauses and deviates from the text definition

### ISSUE THREAD

**Issue by cmungall** [biobanking/biobanking#96]
text definition: A biobank is a collections[sic] of samples of biological substances
(e.g. tissue, blood, DNA) which are linked to data about the samples and their donors. They have a dual nature as collections of samples and data.

This is wildly different from the OWL definition

```owl
'object aggregate'
 and ('has part' some 
    ('object aggregate'
     and ('has part' only 
        (specimen
         and ('participates in' some storage)))))
 and ('has part' some 
    ('material information bearer'
     and ('participates in' some 
        ('digital curation'
         and (has_specified_output some 
            ('data set'
             and ('is about' some 
                ('object aggregate'
                 and ('has part' only specimen)))))))))
 and ('is owned by' some 'biobank organization')
```

the [OBO principles for definitions](https://obofoundry.org/principles/fp-006-textual-definitions.html) state that "Logical definitions, when present, should agree with textual definitions and vice versa". This is less clear wording than I would like (see also: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/908) but I think even with this wording the principle is not upheld here.

The OWL definition is way too complex. It's unlikely you get any useful inference from this. It's not clear why you even need an OWL definition, this should be broken into simpler subClassOf axioms.

Note the OWL definition has clauses that mix cardinality and universal restrictions. This is almost always a mistake. In this case the inner expression evaluates to specimens that are literally atoms, they have no further parts. This is a mistake but the ontology doesn't have the axioms that would make a reasoner catch that. It's likely you need to use has-member or has-component here. But really I would strongly recommend keeping OWL axioms simple, using standard constructs like existentials, with as little nesting as possible, and following the textual definition

**Comment by mbrochhausen** [comment]
Many thanks, Chris! This is helpful. We will look into the matter, but it might take you a couple of weeks to resolve it.

**Comment by cmungall** [comment]
No rush. I was just looking at axiom complexity across obo

**Comment by mbrochhausen** [comment]
Thanks, I appreciate it!

I still think we are taking the faulty axiom out asap and then work on
replacements over the next couple of weeks.

**Comment by CDowland** [comment]
Here's a two-part proposal for updating _biobank_. The first part is a new term that will aid in capturing that the existence of data about the specimens is key the collection being a biobank, but without presupposing that the data is owned or stored by the biobank organization. 

The new term represents such collections of data and is used in the proposed subclass axiom for _biobank_.

**NEW TERM: ‘biobank data collection’:**
Term label: 
‘biobank data collection’

Parent term: 
IAO: ‘information content entity’

Definition: 
Information content entity that is a collection of other information content entities that are about specimens in the same biobank.

SubClass Of:
'has member' some ('information content entity' and 'is about' some (specimen and 'member of' some biobank))


**UPDATED VERSION OF ‘biobank’:**
Term label: 
‘biobank’

Parent term: 
OBI: ‘collection of specimens'

Textual definition: 
Collection of specimens that are of biological relevance and that are linked to data about them and their donors.

SubClass Of:
'has member' some (specimen and inverse 'is about' some ('information content entity' and 'member of' some 'biobank data collection'))

**Comment by mbrochhausen** [comment]
Discussion in the OBIB meeting 04/27/2023:
change label "biobank data collection" might need to be changed to avoid ambiguity of the verb collection referring to both the process of  collecting something and the outcome.

**Comment by mbrochhausen** [comment]
One of the possible solutions discussed (and rejected during the call) was "specimen data". The reason for rejection was that "data" is plural and would thus go against the convention not to use plural in labels.
I think there is sufficient support of seeing data as a singular mass noun (too):
"The [Oxford English Dictionary](https://en.oxforddictionaries.com/#m_en_gb0205520) refers to ‘data’ as a “mass noun, similar to a word like information, which cannot normally have a plural and which takes a singular verb. Sentences such as ‘data was’ (as well as data were) collected over a number of years are now widely accepted in standard English.” https://digitalblog.ons.gov.uk/2016/12/08/data-is-versus-data-are/#:~:text=The%20Oxford%20English%20Dictionary%20refers,widely%20accepted%20in%20standard%20English.%E2%80%9D

 In digital technology, data is usually treated as a singular mass noun to mean “digitally stored information.” 
https://www.thesaurus.com/e/grammar/data-is-or-data-are/

"Data leads a life of its own quite independent of datum, of which it was originally the plural. It occurs in two constructions: as a plural noun (like earnings), taking a plural verb and plural modifiers (such as these, many, a few) but not cardinal numbers, and serving as a referent for plural pronouns (such as they, them); and as an abstract mass noun (like information), taking a singular verb and singular modifiers (such as this, much, little), and being referred to by a singular pronoun (it). Both constructions are standard. The plural construction is more common in print, evidently because the house style of several publishers mandates it.
https://www.merriam-webster.com/dictionary/datum

So, I would feel comfortable using it as a singular mass noun, based on this evidence which includes two statements from Dictionaries (I don't have direct access to the OED, but I trust a British government blog writer that they do and that they can read and understand the dictionary).

**Comment by CDowland** [comment]
Another option is to use "databank," which is defined by the Cambridge Dictionary as follows: "a large collection of information that can be searched quickly, especially using a computer" [https://dictionary.cambridge.org/us/dictionary/english/databank](https://dictionary.cambridge.org/us/dictionary/english/databank)

Webster's defines "data bank" simply as "database," which it defines as "a usually large collection of data organized especially for rapid search and retrieval (as by a computer)"  [https://www.merriam-webster.com/dictionary/data%20bank](https://www.merriam-webster.com/dictionary/data%20bank) ;  [https://www.merriam-webster.com/dictionary/database](https://www.merriam-webster.com/dictionary/database)

While "database" was rejected as an option, I'm guessing that is (in part, at least) because it is ambiguous with respect to whether it denotes a collection of data or instead a system in which data is stored/organized. But I think "databank" avoids that ambiguity. 

While the label 'biobank databank' is a bit awkward, it is an accurate label and it avoids the concerns raised thus far about other options.

**Comment by cmungall** [comment]
I think my main concerns have been addressed, thank you!

For everything else, I don't have any particular insight or expertise, but I have my usual position on this: there are probably about a dozen or so equally good different ways to model biobank. It could be an organization, a physical facility, an object aggregate, an abstract conflated mix of data and physical specimens, and so on. It seems a lot of ontologies in OBO like to solve these things individually but I think it's better to have consistent patterns across all of OBO than to have the most ontologically perfect class, so it seems you might want to elevate some of this to the OBI/COB level (unless there are particular non-ontological use cases)

I'd also urge for simplicity and conventional terminology.

**Comment by mbrochhausen** [comment]
I think we did all that given the long time this ontology has been around. 

BTW we have biobank site and biobank organization.

**Comment by mbrochhausen** [comment]
Thanks, Chris, for pointing out the faulty axiom and for taking the time to check the revised version.

As your comment is also visible to third parties, I am going to take the time to respond.

OBIB has indeed a representation for biobank organization (http://purl.obolibrary.org/obo/OBIB_0000623) in addition to biobank (http://purl.obolibrary.org/obo/OBIB_0000616). We currently do not have biobank facility, but we are sure that a representation for that can be easily post-coordinated using OBIB and other OBO Foundry ontologies.

For some of your other comments, it is helpful to know and understand the history of the development of OBIB. One of the ontologies that started OBIB was OMIABIS, an ontology developed in close collaboration with BBMRI-ERIC (https://www.bbmri-eric.eu/services/other-services/), a multinational, European network to facilitate data and specimen sharing among participating nations. The "abstract conflated mix of data and physical specimens", while maybe providing some headaches for ontologists was a requirement by the use case towards which the project was working. It was grounded in the European legal situation at the time and hence, could not have been avoided. The goal of OMIABIS was providing an ontological representation for BBMRI-ERIC's Minimum Information About BIobank data Sharing (MIABIS).
This work was done in 2013. At time at which COB was certainly not in existence and ontology patterns were used way less frequently and certainly were not as popularized by the OBO Foundry as they rightfully are today. As many members of the OBIB team are longterm contributors, supporters, and advertisers of the OBO Foundry, they whole-heartedly support the Foundry's push to more consistent and more rigorous development methodologies. However, I assume it goes without saying that development that was done before those methods and protocols were implemented, should not be criticized for not following those methodologies. 
I, personally, are particularly interested in your remark regarding conventional terminology. Could you give an example where OBIB does, in your opinion, not follow conventional terminology? As pointed out above the initial work on this ontology was done in close collaboration with domain experts, who had already created data elements and reconciled terminologies. Notably, the work on OMIABIS (now included in OBIB) had a paper on terminology for biobanking as its output (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4266732/).

**Comment by CDowland** [comment]
Following up here with the outcomes of discussions on this. Below is the revised version of 'biobank', followed by a new term that it uses.  


**Revised version of ‘biobank’:**
Term label:
‘biobank’
Parent term:
OBI: ‘collection of specimens'
Textual definition:
Collection of specimens that are of biological relevance and that are linked to data about them and their donors.
SubClass Of:
'has member' some (specimen and inverse 'is about' some ('information content entity' and 'member of' some 'biobank databank))


**New term, ‘biobank databank’:**
Term label:
‘biobank databank’
Parent term:
IAO: ‘information content entity’
Definition:
Information content entity that is a collection of other information content entities that are about specimens in the same biobank.
SubClass Of:
'has member' some ('information content entity' and 'is about' some (specimen and 'member of' some biobank))

Notes: The previous definition of 'biobank' described it as a collection of specimens that are linked to data, but also emphasized its "dual nature" as a collection of specimens and data about them. This was potentially confusing with respect to whether the data items are members of the collection or not. With these revisions to 'biobank,' it is more clear that the biobank is the collection of specimens only, while still requiring there be data about the specimens. We represent that type of collection of data with the new term above, 'biobank databank.'
